Assets/Scenes/SampleScene.meta
Assets/Scenes/SampleScene.unity

- Edited maze layout
- Added more building colliders
- Created NavMesh (can't see it though)
- Created waypoints

Edited maze pt2

---

Assets/Scenes/SampleScene.unity

Removed errors wih tree branch mesh colliders

Cleaned up errors

---

Assets/MazeFlagCollisionCode.cs
Assets/MazeFlagCollisionCode.cs.meta
Assets/MazeSheepAI.cs
Assets/Models/Characters.meta
Assets/Scenes/SampleScene.unity

Now if the player crosses an invisible border, it will trigger sheep walking on waypoints

More sheep AI (walk on trigger)

---

Assets/BehindSphereColliderScript.cs
Assets/BehindSphereColliderScript.cs.meta
Assets/FrontBoxColliderScript.cs
Assets/FrontBoxColliderScript.cs.meta
Assets/MazeFlagCollisionCode.cs
Assets/MazeSheepAI.cs
Assets/Scenes/SampleScene.unity
ProjectSettings/TagManager.asset

- Sheep now detects player from back: stops and waits, if player stays, it turns to it
- Sheep now detects player from front: stops completly
New scripts: FrontBoxColliderScript, BehindSphereColliderScript

Finished sheep AI

---

Assets/Scenes/StarUIScene.unity
Assets/Scripts/CollectableStar.cs
Assets/Scripts/Player/CharacterInputController.cs
Assets/Scripts/StarCollector.cs

- can only use sneak if the first star was collected
- added a star array with boolean values to keep track of what stars are collected & allow using those powerups

Player Sneak Logic

---

Assets/Scenes/StarUIScene.unity

- tells player they were caught
- UI with buttons for restart and main menu

Added Player Caught PopUp

---

Assets/Prefabs/HomeBase.prefab
Assets/Prefabs/HomeBase.prefab.meta
Assets/Prefabs/UI.prefab
Assets/Prefabs/UI.prefab.meta
Assets/Scenes/AllStarsCollected.unity
Assets/Scenes/AllStarsCollected.unity.meta
Assets/Scenes/End.unity
Assets/Scenes/End.unity.meta
Assets/Scripts/TriggerEnd.cs
Assets/Scripts/TriggerEnd.cs.meta
ProjectSettings/EditorBuildSettings.asset

- if you collect 1 star and go to home base platform it cues end scene
- base platform is prefabbed
- UI from previous commits is a prefab

Added End Condition

---

Assets/AnimatorControllers/Main Maze Sheep AnimController.controller
Assets/Scenes/CarryStarScene.unity
Assets/Scripts/PlaceItemDownTrigger.cs
Assets/Scripts/PlaceItemDownTrigger.cs.meta
ProjectSettings/TagManager.asset

-added trigger box on bench
-when star collider collides with trigger box, sheep putting down item animation plays

sheep put down item animation

---

Assets/Animations/PlaceItemDown.anim
Assets/AnimatorControllers/Star Animator Controller.controller
Assets/AnimatorControllers/Star Animator Controller.controller.meta
Assets/Scenes/CarryStarScene.unity

18 carry drop star

---

Assets/Prefabs/Main Maze Sheep.prefab
Assets/Prefabs/Main Maze Sheep.prefab.meta
Assets/Prefabs/PutStarDownTrigger.prefab
Assets/Prefabs/PutStarDownTrigger.prefab.meta
Assets/Scenes/CarryStarScene.unity
Assets/Scenes/SampleScene.unity

-put in maze sheep from CarryStarScene
-put in PutDownTrigger into samplescene

put in maze sheep from CarryStarScene into SampleScene

---

Assets/Models/Characters.meta
Assets/Prefabs/UI.prefab
Assets/Prefabs/UI.prefab.meta
Assets/Scenes/SampleScene.unity
Assets/Scenes/StarUIScene.unity

- moved the prefabbed homebase
- UI for game
- other items that were made in starUIScene

Merging StarUIScene Items

---

Assets/AnimatorControllers/Main Maze Sheep AnimController.controller
Assets/Models/Characters.meta
Assets/Scenes/CarryStarScene.unity
Assets/Scripts/PlaceItemDownTrigger.cs

-child object star is destroyed after it is placed on the bench/table
-new star is set active when the old star is destroyed

updated CarryStarScene

---

Assets/Prefabs/newStarCollect.prefab
Assets/Prefabs/newStarCollect.prefab.meta
Assets/Scenes/CarryStarScene.unity
Assets/Scenes/SampleScene.unity

-added newStarCollect to scene
-newStarCollect is disabled at first and enabled/set active when old star is placed on bench

merge replace star into samplescene

---

Assets/Scenes/FixBrightnessScene.unity
Assets/Scenes/FixBrightnessScene.unity.meta

-fixed brightness and lightsource

added fixbrightnessscene

---

Assets/Models/Characters.meta
Assets/Scripts/PlaceItemDownTrigger.cs

-fixed old star so that it gets destroyed before sheep moves away

fixed star disappearance

---

Assets/Models/Characters.meta
Assets/Scenes/SampleScene.unity
Assets/Scripts/TriggerEnd.cs

- player can collect maze star
- if player returns to homebase platform with 2 stars collected, end scene
- re-enabled game ui

Allow Player to Collect Maze Star

---

Assets/Scenes/SampleScene.unity

Added a collider to the table as the player was able to go through it

Added collider to table

---

Assets/Models/Characters.meta
Assets/Scenes/SampleScene.unity

-added 2 canvas prefabs to hierarchy/scene
1. countdown on screen (countdown value can be changed in GameOverCanvas->GameOverMenuTimeIn script->timeout public variable)
2. added gameover screen with restart and quit buttons when times out

added timer and gameover ui

---

Assets/Scenes/SampleScene.unity

- added exit button, changed names

Updated Pause UI

---

Assets/ContinueGame.cs
Assets/ContinueGame.cs.meta
Assets/Models/Characters.meta
Assets/RestartLevel.cs
Assets/ReturnToMainMenu.cs
Assets/Scenes/MainMenu.unity
Assets/Scenes/SampleScene.unity
Assets/Scripts/PauseMenuToggle.cs
Assets/Scripts/PauseMenuToggle.cs.meta
ProjectSettings/EditorBuildSettings.asset
ProjectSettings/TagManager.asset

- Connected buttons in main menu and pause mennu to script
- Issue: continue button in Pause screen doesn't work

Connected buttons to script

---

Assets/Prefabs/PlantStar.prefab
Assets/Prefabs/PlantStar.prefab.meta

- placed prefab into main scene
- disabled bridge

Plant& star

---

Assets/AnimatorControllers/Starboy.controller
Assets/PlantAction.cs
Assets/Scripts/Player/CharacterInputController.cs
Assets/Scripts/StarCollector.cs

- script for each interaction is set up to play the correct animation when the right conditions are met

Interaction Animation Skeleton

---

Assets/Animations/Textbox.controller
Assets/Animations/Textbox.controller.meta
Assets/Animations/Textbox_close.anim
Assets/Animations/Textbox_close.anim.meta
Assets/Animations/Textbox_open.anim
Assets/Animations/Textbox_open.anim.meta
Assets/NewspaperSheep.cs
Assets/NewspaperSheep.cs.meta
Assets/Scenes/NewspaperPlayer.unity.meta
Assets/Scripts/Dialogue.meta
Assets/Scripts/Dialogue/Dialogue.cs
Assets/Scripts/Dialogue/Dialogue.cs.meta
Assets/Scripts/DialogueManager.cs
Assets/Scripts/DialogueManager.cs.meta
Assets/Scripts/Player/CharacterInputController.cs
Assets/Scripts/StarCollector.cs
Assets/StartQuest.cs
Assets/StartQuest.cs.meta
Assets/TextboxToggle.cs
Assets/TextboxToggle.cs.meta
ProjectSettings/TagManager.asset

- sheep NPC with dialogue set up for before and after quest
- newspaper box for initiating quest
- star that emerges from sheep after complete quest
- player can talk through dialogue
-general dialoguemanagement system
-UI for newspaper quest set up

Player Newspaper Implementation

---

Assets/Prefabs/NewspaperScene.meta
Assets/Prefabs/NewspaperScene/DialogueManager.prefab
Assets/Prefabs/NewspaperScene/DialogueManager.prefab.meta
Assets/Prefabs/NewspaperScene/Newspaper Sheep.prefab
Assets/Prefabs/NewspaperScene/Newspaper Sheep.prefab.meta
Assets/Prefabs/NewspaperScene/Newspapers.prefab
Assets/Prefabs/NewspaperScene/Newspapers.prefab.meta
Assets/Prefabs/NewspaperScene/NumProgress.prefab
Assets/Prefabs/NewspaperScene/NumProgress.prefab.meta
Assets/Prefabs/NewspaperScene/Sheep Talk.prefab
Assets/Prefabs/NewspaperScene/Sheep Talk.prefab.meta
Assets/Prefabs/NewspaperScene/newspaper_star Variant.prefab
Assets/Prefabs/NewspaperScene/newspaper_star Variant.prefab.meta

- cleaned up hierarchy of main scene

Merged Newspaper player scene

---

Assets/Animations/Float Small.anim
Assets/Animations/Float Small.anim.meta
Assets/Animations/New Animation.anim
Assets/Animations/New Animation.anim.meta
Assets/Animations/orbit.anim
Assets/Animations/orbit.anim.meta
Assets/AnimatorControllers/Orbit Animator.controller
Assets/AnimatorControllers/Orbit Animator.controller.meta
Assets/Scenes/CollectableStar.unity.meta
Assets/Scripts/StarCollector.cs

- when player collects stars, it they will translate to mini stars that orbit above the player's head
- added orbit and float animations
- skeleton for these stars on player

Collectable Star Orbit

---

Assets/Prefabs/MushroomArea.prefab
Assets/Prefabs/MushroomArea.prefab.meta
Assets/Prefabs/RockArea.prefab
Assets/Prefabs/RockArea.prefab.meta
Assets/Prefabs/stars.prefab
Assets/Prefabs/stars.prefab.meta

moved orbiting stars and areas into main

Player Stars Orbit Merged

---

Assets/Scenes/WellEndGame.unity.meta
Assets/Scripts/DialogueManager.cs
Assets/Scripts/Player/CharacterInputController.cs
Assets/Scripts/StarCollector.cs
Assets/Scripts/TriggerEnd.cs

- well is set up to end game when stars are collected
- dialogue appears, disabling player movement, and then it goes to cutscene end scene

Wishing Well End Game

---

Assets/AnimatorControllers/Starboy.controller
Assets/Prefabs/UI Variant.prefab
Assets/Prefabs/UI Variant.prefab.meta
Assets/Scripts/DialogueManager.cs

- dont let player dance when in dialogue mode
- cleaned up UI to be constrained correctly
-removed unnecessary duplicates

Prevent Long Idle

---

Assets/ActionRock.cs
Assets/ActionStar.cs
Assets/ActionStar.cs.meta
Assets/Animations/FlipRock.anim
Assets/Animations/Star Float.anim
Assets/Animations/Star Float.anim.meta
Assets/AnimatorControllers/Rock Animator.controller
Assets/AnimatorControllers/RockStar Anim Controller.controller
Assets/AnimatorControllers/RockStar Anim Controller.controller.meta
Assets/RockStar_Rend.cs
Assets/RockStar_Rend.cs.meta

Rock and star interaction

---

Assets/NewspaperAction.cs
Assets/NewspaperAction.cs.meta
Assets/Prefabs/cloud_final 1.prefab

- Added a newspaper into the scene
- Collision of newspaper to colored houses (not unique to color)

Newspaper set up

---

Assets/Animations/Newspaper Flying.anim
Assets/Animations/Newspaper Flying.anim.meta
Assets/AnimatorControllers/Newspaper Anim Controller.controller
Assets/AnimatorControllers/Newspaper Anim Controller.controller.meta
ProjectSettings/TagManager.asset

Set up the animator controller and animation for newspaper.
No animation is there yet.

Newspaper anim setup

---

Assets/Materials/Colors/Pink.mat
Assets/Prefabs/large-cloud-rock.prefab
Assets/Prefabs/medium-cloud-rock.prefab
Assets/Prefabs/small-cloud-rock.prefab

-changed cloudrocks material to material001 (cloud platform material)
-changed Pink material to be less shiny

changed cloudrocks material

---

Assets/Newspaper.cs
Assets/Newspaper.cs.meta
Assets/NewspaperAction.cs
Assets/Prefabs/newspaper Variant.prefab
Assets/Prefabs/newspaper Variant.prefab.meta
Assets/Scripts/StarCollector.cs

- newspaper game object instantiated when throw button s is pressed
- destroyed when it collides with anything thats not the player
-scripts necessary attached to both gameobject newspaper and newspaper model to handle collisions and physics behind throwing

Newspaper thrown

---

Assets/HouseNewspaperCounter.cs
Assets/HouseNewspaperCounter.cs.meta
Assets/NewspaperAction.cs
Assets/NewspaperSheep.cs
Assets/Scripts/StarCollector.cs
ProjectSettings/TagManager.asset

- Added house colliders
- Added script on houses that indicate how many newspapers are needed for each. and if the correct number is delivered
- Added an on screen counter of newspapers delivered

Newspaper action

---

Assets/Newspaper.cs
Assets/Scripts/Player/CharacterInputController.cs
Assets/Scripts/StarCollector.cs
Assets/StartQuest.cs

- create new UI for newspaper mission, hook up to remaining and delivered variables
- adjust textbox to stretch with screen
- cap newspapers being thrown

Newspaper UI and cap

---

Assets/HouseNewspaperCounter.cs
Assets/Scripts/StarCollector.cs

- Made it so that only newspapers delievred in correct amounts to houses would trigger the increment of newspapers delievred.
- Changed newspapers needed from 7 to 22

Newspaper fix

---

Assets/Scripts/UI/CountdownTimer.cs
Assets/Scripts/UI/GameOverMenuTimeIn.cs

-changed float variables to int in gameovermenutimein script and countdown timer script
-edited countdown timer script to calculate minutes from seconds to display minutes and seconds instead of just seconds on Countdown UI

changed timer seconds to minutes and seconds

---

Assets/Scripts/UI/GameOverMenuTimeIn.cs

-increased timeout to 5 minutes (300 seconds)
-changed GameOverMenuTimeIn script so that GameOver time out menu does not show when player collects all 7 stars

fixed timer issue

---

Assets/ReturnToMainMenu.cs
Assets/Scripts/UI/CountdownTimer.cs

- unpaused time so that animation can play when going from the pause menu to main menu
- changed timer text to time

Pause to Main

---

Assets/Animations/tree_star.controller
Assets/PlantAction.cs
Assets/Scripts/CollectableStar.cs
Assets/Scripts/ShakeTree.cs
Assets/Scripts/StarCollector.cs

- fixed plant and tree interactions bug
- needed to rearrange when interacted was being set back to false & add it in for tree

Interactions

---

Assets/Scripts/DialogueManager.cs
Assets/Scripts/UI/CountdownTimer.cs
Assets/StartQuest.cs

- adjustments to placement, font, font size, and text
- organized newspaper ui into a panel

UI updates for all

---

Assets/Scripts/Player/CharacterInputController.cs

- only be able to throw newspaper when in quest

Throwing Newspaper

---

Assets/Animations/Elevator 1.controller
Assets/Animations/Elevator 1.controller.meta
Assets/Animations/Elevator.controller
Assets/Animations/ElevatorMoving.anim
Assets/Animations/ElevatorVerticalMovement.anim
Assets/Animations/ElevatorVerticalMovement.anim.meta
Assets/Materials/Materials.meta
Assets/Materials/Materials/TexturesCom_WoodFine0086_7_seamless_S.mat
Assets/Materials/Materials/TexturesCom_WoodFine0086_7_seamless_S.mat.meta
Assets/Prefabs/ElevatorRoot.prefab
Assets/Prefabs/ElevatorRoot.prefab.meta
Assets/Scenes/FixElevevatorScene.unity.meta

-made waiting platform for elevator
-made a ramp so that player can get to elevator when going up
-changed animation so that the elevator only goes up vertically

fixed elevator

---

Assets/Animations/Star Fall.anim
Assets/Animations/tree_star.controller
Assets/Scripts/ShakeTree.cs

-added trunk and branch colliders to treestar (TREE)
-changed tree_star (STAR) animation so it is more visible to player

fixed treestar animation

---

Assets/MazeSheepAI.cs

It resets the whole game though

Just some AI restart stuff

---

Assets/Prefabs/ControlsMenu.prefab
Assets/Prefabs/ControlsMenu.prefab.meta
Assets/Scenes/MainMenu.unity

-added access to controls menu to the in game menu

Controls to in game

---

Assets/AnimatorControllers/Starboy.controller
Assets/Scripts/Player/CharacterInputController.cs

filtered movement a bit, works fine for left side - right side animations dont blend well

Player filtering

---

Assets/Scripts/CameraFollow.cs
Assets/Scripts/Player/ThirdPersonCamera.cs
ProjectSettings/TagManager.asset

-added scripts in progress for new camera movement

Camera Follow

---

Assets/Animations/Walking.anim
Assets/AnimatorControllers/Starboy.controller
Assets/Scripts/CameraFollow.cs
Assets/Scripts/Player/CharacterControllerScript.cs
Assets/Scripts/Player/CharacterInputController.cs

- player has new camera movement
- script adjustments and using camerafollow script for main instead
- player can turn completely infront of camera
- when player walks towards camera, it repositions to be behind
- still using filtered input

Camera orbit

---

Assets/MazeSheepAI.cs
Assets/Scripts/DialogueManager.cs
Assets/WoodChopperTextScript.cs

- Changed time to 15 minutes (900 seconds)
- Sank in some rocks
- AI walks fucntions correctly

Fixed AI, increased time

---

Assets/NewspaperSheep.cs
Assets/Scripts/DialogueManager.cs
Assets/StartQuest.cs

- can only start quest when you first talk to the sheep and then go to the box
- inventory ui disappears when you complete the quest

Quest Start & End

---

Assets/FarmerSheep.cs
Assets/RockhintSheep.cs
Assets/Scripts/DialogueManager.cs
Assets/TreehintSheep.cs

- added to dialog manager script a first time indicator
- for use by npcs that always need to repeat the SAME dialog

Dialog Restart

---

Assets/Animations/StarCollectionText.controller
Assets/Animations/StarCollectionText.controller.meta
Assets/Animations/Text_IN.anim
Assets/Animations/Text_IN.anim.meta
Assets/Animations/Text_OUT.anim
Assets/Animations/Text_OUT.anim.meta
Assets/Animations/Textbox_open.anim
Assets/Low Poly Water/Plane Meshes/water3x3W30H20.asset
Assets/Scripts/StarCollector.cs

- text displays that you've collected a star
- animated so that it scrolls onto screen and leaves (timed with the player movement pause/restart)

Star Collect Text

---

Assets/ActionRock.cs
Assets/AllowCollection.cs
Assets/AllowCollection.cs.meta
Assets/Animations/Stars.meta
Assets/Animations/Stars/FloatUp.anim
Assets/Animations/Stars/FloatUp.anim.meta
Assets/Animations/Stars/GameObject.controller
Assets/Animations/Stars/GameObject.controller.meta
Assets/Animations/Stars/PlantRoot.controller
Assets/Animations/Stars/PlantRoot.controller.meta
Assets/PlantAction.cs
Assets/Scripts/CollectableStar.cs
Assets/Scripts/Player/CharacterInputController.cs
Assets/Scripts/StarCollector.cs

- new star floating up animation added to the rock and plant star so that they're not auto-collected
- only allows collection once the animation brings the star back down
- other stars are hardcoded to be collectable
- fixed Rock animation continuously playing after collecting the rock

Star Float and Collection

---

Assets/RootMotionControlScript.cs
Assets/RootMotionControlScript.cs.meta

Added root motion script to AI sheep

Root motion to AI sheep

---

Assets/AnimatorControllers/StarboyHum.controller
Assets/Models/Characters/Player/PlayerMask.mask
Assets/Models/Characters/Player/PlayerMask.mask.meta
Assets/Scripts/Player/CharacterControllerScript.cs

- IK to match hand placement to where plant is

Added IK to plant

---

Assets/Animations/Stars/FloatingIdle.anim
Assets/Animations/Stars/FloatingStar.controller
Assets/Animations/Stars/PlantRoot.controller
Assets/Animations/Stars/SpinTreeStar.anim
Assets/Animations/Stars/SpinTreeStar.anim.meta
Assets/Animations/tree_star.controller
Assets/AnimatorControllers/StarboyHum.controller
Assets/Low Poly Water/Plane Meshes/water3x3W30H20.asset

- all stars now when idle spin 360

All Star Idle Animation

---

Assets/Prefabs/starCollect.prefab
Assets/Scripts/CollectableStar.cs
Assets/Scripts/Player/CharacterControllerScript.cs
Assets/Scripts/Player/CharacterInputController.cs

- can collect is only checked in ontriggerstay to collect it
- adjusted trigger area of collectable stars to be smaller

Double Count Problem Solved

---

Assets/AllowCollection.cs
Assets/Animations/Stars/FloatToSide.anim
Assets/Animations/Stars/FloatToSide.anim.meta
Assets/Animations/Stars/NewsIdle.anim
Assets/Animations/Stars/NewsIdle.anim.meta
Assets/AnimatorControllers/NewsStarAnim.controller
Assets/AnimatorControllers/NewsStarAnim.controller.meta
Assets/NewsStar.cs
Assets/NewsStar.cs.meta
Assets/Scripts/CollectableStar.cs
Assets/Scripts/DialogueManager.cs

- news star appears from out of the box
- floats up and lands at the side, goes to spinning
- canCollect used to allow collection

News Star Reveal Polish

---

Assets/AnimatorControllers/Main Maze Sheep AnimController.controller
Assets/BehindSphereColliderScript.cs
Assets/ControlsTracker.cs
Assets/FrontBoxColliderScript.cs
Assets/MazeSheepAI.cs
Assets/WoodChopperTextScript.cs

- transition back to idle after restarting
- front collision detection
- restarts with front collision

Front Collision AI

---

Assets/Animations/Player/Kicking.anim
Assets/Animations/Player/Shake.anim
Assets/AnimatorControllers/StarboyHum.controller
Assets/Models/Characters/Player/PlayerMask.mask
Assets/Scripts/Player/CharacterControllerScript.cs
Assets/Scripts/Player/CharacterInputController.cs

- updated sheep talk button
- ik for tree shake
- ik for rock and plant

IK and updates

---

Assets/AnimatorControllers/Main Maze Sheep AnimController.controller
Assets/AnimatorControllers/StarboyHum.controller

Sneak Anim and Walk

---

Assets/NewspaperSheep.cs

news throwing

---

Assets/Animations/orbit.anim
Assets/Scripts/StarCollector.cs
ProjectSettings/GraphicsSettings.asset

pause images
last star collect
orbiting

Adjustments
